GET_NAME_COMMAND = "name"
MOVE_LEFT_COMMAND = "motors_manager.move_x(-255)"
MOVE_RIGHT_COMMAND = "motors_manager.move_x(255)"
MOVE_FORWARD_COMMAND = "motors_manager.move_y(255)"
MOVE_BACKWARD_COMMAND = "motors_manager.move_y(-255)"
TURN_LEFT_COMMAND = "motors_manager.turn(-175)"
TURN_RIGHT_COMMAND = "motors_manager.turn(175)"
STOP_MOVING_COMMAND = "motors_manager.stop_moving()"
SERVO_CONTROL_COMMAND = "servos_manager.write_servo(<index>, <angle>)" # replace <index> with index and <angle> with angle
SERVOS_CONTROL_COMMAND = "servos_manager.write_servos_same(<indexes>, <angle>)" # replace <indexes> with a list of indexes and <angle> with an angle
GET_SHOW_NAMES_COMMAND = "get_show_names_str()"
GET_SHOW_STEPS_COMMAND = "get_show_steps_str('<name>')" # replace <name> with the show name
PLAY_SHOW_COMMAND = "run_show('<name>')" # replace <name> with the show name
PLAY_SHOW_FROM_STEP_COMMAND = "run_show('<name>', <step>)" # replace <name> with the show name and <step> with the start step index
PLAY_STEP_COMMAND = "run_show('<name>', <step>, <step>)" # replace <name> with the show name and <step> with the wanted step index
END_SHOW_COMMAND = "end_show()"
GET_RUNNING_COMMAND = "get_running_step_index()"